######################
##   BUILD STAGE    ##
######################

Build:
  stage: build
  image: node:12
  script:
    - yarn install
    - yarn build
    - yarn generate
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: $AWS_DEFAULT_REGION
    S3_BUCKET_NAME: $S3_BUCKET
  script:
    - touch foo.txt
    - aws s3 cp --endpoint-url=https://storage.yandexcloud.net --recursive ./dist s3://$S3_BUCKET/
