stages:
  - build
  - deploy
  - notify
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/


######################
##   BUILD STAGE    ##
######################

Build:
  stage: build
  image: node:alpine
  before_script:
    - apk add zip
  script:
    - yarn install
    - yarn generate
    - zip -r dist.zip dist
  artifacts:
    paths:
      - dist.zip
    expire_in: 1 day

######################
##  DELIVERY STAGE  ##
######################

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp dist.zip root@45.12.18.76:/var/www/kottte
    - ssh root@45.12.18.76 "cd /var/www/kottte; unzip dist.zip"
    - sh .ci-notify.sh ✅

notify_error:
  stage: notify
  script:
    - sh .ci-notify.sh ❌
  when: on_failure #deploy fail
