stages:
  - build
  - deploy
  - notify
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/


######################
##   BUILD STAGE    ##
######################

Build:
  stage: build
  image: node:alpine
  script:
    - yarn install
    - yarn generate
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

######################
##  DELIVERY STAGE  ##
######################

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: $AWS_DEFAULT_REGION
    S3_BUCKET_NAME: $S3_BUCKET
  script:
    - aws s3 rm s3://$S3_BUCKET/_nuxt/ --recursive
    - aws s3 cp --recursive --include "*" ./dist s3://$S3_BUCKET/
    - sh .ci-notify.sh ✅

notify_error:
  stage: notify
  script:
    - sh .ci-notify.sh ❌
  when: on_failure #deploy fail
