deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: $AWS_DEFAULT_REGION
    S3_BUCKET_NAME: $S3_BUCKET
  script:
    - aws configure --endpoint-url=https://storage.yandexcloud.net
    - touch foo.txt
    - aws s3 cp --recursive foo.txt s3://$S3_BUCKET/
